AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Rod in AWS Lambda

Resources:
  GetPageHTMLFunction:
    Type: AWS::Serverless::Function
    Properties: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 1200 # for just getting html, memory very infrequently goes above 1000
      Timeout: 30
      FunctionUrlConfig: # creates a function url
        AuthType: NONE
    Metadata:
      DockerTag: latest
      DockerContext: ./
      Dockerfile: ./Dockerfile
